name: Retrieve version and update via semantic-release

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
        description: "Sonarcloud Token"
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Run Sonarcloud Report
        run:  ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=${GITHUB_REF##*/}
